### PR TITLE
it was ok before the fix

### PR DESCRIPTION
**Pull request by luisabellan**

### CODE REVIEW

**Comment by williamschwindt** [comment]
Can we switch it to table.increments('id')?
Using that is the same as "id, int, unsigned, not null, auto_increment, primary key"  and then doesn't require id to be in the request body.

**Comment by luisabellan** [comment]
> Can we switch it to table.increments('id')?
> Using that is the same as "id, int, unsigned, not null, auto_increment, primary key" and then doesn't require id to be in the request body.

you are not supposed to send the id in the post request, they are created automatically.

**Comment by williamschwindt** [comment]
I understand but either they aren't being created automatically or they are not incrementing because when I was testing my post route in insomnia it threw an error unless I added ID in the request body

**Review by williamschwindt — APPROVED** [review]

**Comment by luisabellan** [comment]
@williamschwindt tested it with Insomnia

**Review by coryortega — APPROVED** [review]

**Pull request merged**
