### PR TITLE
customer/groomer router and model set up

### PR DESCRIPTION
**Pull request by williamschwindt**
Routes for Groomers and Customers set up for the front-end to retrieve information from the database.
Skeleton code created for release 1 routes.
API Documentation: https://app.swaggerhub.com/apis/LabsPT12TeamA/Express_Groomer/1.0.0#trial

### CODE REVIEW

**Comment by williamschwindt** [comment]
Customers and groomers model files will have to be updated once Luis's PR "Created tables and added some dummy data for each table to kick off the project" is merged.
The current schema's tables are Customer and Groomer but will be switched to customers and groomers post merge.

**Review by coryortega — COMMENTED** [review]
Great job setting up the skeleton routes for release 1

**Comment by williamschwindt** [comment]
Logic done with the exception of groomer search.
Routes have been tested in Insomnia but automated tests still need to be written.

**Review by coryortega — APPROVED** [review]
Nice work!

**Review by coryortega — APPROVED** [review]

**Review by RobertElias — APPROVED** [review]
Great work William.

**Review by luisabellan — APPROVED** [review]
It looks good!

**Pull request merged**
